### ISSUE TITLE
Create the Navbar menu with the search and profile 

### ISSUE THREAD

**Issue by iamsethsamuel** [devxp-projects/devxp_react_projects#43]
Make sure everything looks the same as in the Figma design. Let the view be Responsive for mobile, table and Desktop

**Comment by baraqkenny** [comment]
I am interested in addressing this particular issue.

**Comment by Promtech1** [comment]
I want to work on this.

**Comment by iamsethsamuel** [comment]
> I want to work on this.

How far about this

**Comment by NwekeMaxwell** [comment]
Implemented yet? If no, I'd like to collaborate

**Comment by iamsethsamuel** [comment]
> Implemented yet? If no, I'd like to collaborate

You can just go ahead and implement it. Seems like  he would complete it
