### ISSUE TITLE
Create the Calendar section

### ISSUE THREAD

**Issue by iamsethsamuel** [devxp-projects/devxp_react_projects#48]
This is the section the has the  ***Lifestyle:  3.3 PAYDAY 2022    15% off min spend SGD 100   HOME10***. It should be a component and the data should come from a JSON file.

**Comment by Gabbiedee** [comment]
I will take up this issue

**Comment by iamsethsamuel** [comment]
> I will take up this issue

How far about this?

**Comment by Gabbiedee** [comment]
Hi Seth,
I was the one that chatted you up on Slack about the need to defer to the
next cohort.
Thank you

**Comment by NwekeMaxwell** [comment]
Oh great, I'll take this up then.
I'm open to collaborate with anyone interested.
This section looks interesting
